# src/ui/pages/triage_dashboard.py — Results & History Dashboard
#
# PURPOSE:
#   Streamlit page that displays:
#   - History of processed bug reports
#   - Aggregate metrics (avg latency, total cost, token usage)
#   - Cost estimation for 100 queries
#   - Error rate and system health indicators
#
# DATA SOURCE:
#   Reads from data/temp/metrics.jsonl and data/temp/audit.jsonl
#   generated by the telemetry module.
#
# TODO:
#   - Load and display metrics from JSONL files
#   - Build charts for latency, cost, and token usage trends
#   - Show recent audit trail entries in a table
#   - Add cost projection calculator

import streamlit as st
